services:
  db:
    image: postgres:17
    container_name: postgres17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio
    ports:
      - "5432:5432"
    # volumes:
      # - db_data:/var/lib/postgresql/data

# volumes:
  # - ./docker/setup.sql:/docker-entrypoint-initdb.d/init.sql