POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Curso de Docker"
}

####

GET http://localhost:3333/courses



####

GET http://localhost:3333/courses/ceded666-5e23-41f4-b511-490c8108f6ed