POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Curso de Docker"
}

####

GET http://localhost:3333/courses



####

GET http://localhost:3333/courses/97946241-39a1-4184-aced-f646ce03be3c